/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

package basics.ProjectEulerIToX;

public class ProjectEulerTwo {
    public static void main (String [] args){
        long sum = 2; // start with 2 becaue the first hard-coded 2 needs to be included in the sum
        long numOne = 1;
        long numTwo = 2;
        long numThree = 0;
        while (numThree <= 4000000){ // for all fibonnaci numbers not more than 4000000
            numThree = numTwo + numOne; //numThree is current number of fibonnaci sequence
            numOne = numTwo; //the number immediately previous becomes 2 previous
            numTwo = numThree; //the current number becomes previous
            if(numThree % 2 == 0){
                sum+= numThree;
            }
        }
        System.out.println(sum);
    }
}
